owner: manticoresoftware
repo: upptime
user-agent: manticoresoftware/upptime

secrets: []

sites:
  - name: Slack Community
    url: https://slack.manticoresearch.com
    maxRedirects: 0
    expectedStatusCodes:
      - 302
  - name: Manual
    url: https://manual.manticoresearch.com/
  - name: Manual (dev)
    url: https://manual.manticoresearch.com/dev/
  - name: Playground
    url: https://play.manticoresearch.com/
  - name: Did You Mean Playground
    url: https://play.manticoresearch.com/didyoumean/
  - name: MySQL Playground
    url: https://play.manticoresearch.com/mysql/
  - name: Package Repository
    url: https://repo.manticoresearch.com
  - name: Community Forum
    url: https://forum.manticoresearch.com
  - name: Documentation
    url: https://docs.manticoresearch.com
  - name: Chat
    url: https://chat.manticoresearch.com
  - name: Facet Demo
    url: https://facet.manticoresearch.com
  - name: Image Search Demo
    url: https://image.manticoresearch.com
  - name: GitHub
    url: https://github.manticoresearch.com
  - name: Catalog Demo
    url: https://catalog.manticoresearch.com

status-website:
  baseUrl: /upptime
  logoUrl: https://manticoresearch.com/images/logo.svg
  name: Manticore Search Status
  introTitle: "**Manticore Search** service status"
  introMessage: Availability and response-time history for Manticore Search public services.
  navbar:
    - title: Status
      href: /upptime/
    - title: Manticore Search
      href: https://manticoresearch.com
    - title: GitHub
      href: https://github.com/manticoresoftware/upptime
